name: Java CI with Maven

env:
  UPLOAD_URL: https://uploads.github.com/repos/MarginallyClever/Makelangelo-software/releases/54908875/assets{?name,label}
  RELEASE_ID: 54908875

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        jdk_version: [22, 17]
        jvm_flag:
          - "-XX:+UseG1GC"
          - "-XX:+UnlockExperimentalVMOptions"
          - "-XX:+UseStringDeduplication"
          - "-XX:+UseCompressedOops"
          - "-XX:+OptimizeStringConcat"
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Generate timestamp
      id: timestamp
      run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
           echo "::set-output name=time::$(date +'%Y%m%d%H%M%S')"


    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      timeout-minutes: 15
      env:
        MAVEN_OPTS: ${{ matrix.jvm_flag }}
      run: ./mvnw -B test -Djava.awt.headless=true

    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk_version }}

    - name: Tell a JVM Joke
      run: |
          echo "Why did the JVM go to therapy? It had too many unresolved flags! 😂"

    - name: Package with Maven
      run: ./mvnw -B clean package -DskipTests

    - name: Prepare universal package
      shell: bash
      run: |
        mkdir -p target/universal-package &&
        cp src/main/package/*.bat target/universal-package/ &&
        cp src/main/package/start* target/universal-package/ &&
        cp src/main/package/thankyou.* target/universal-package/ &&
        cp CONTRIBUTING.md target/universal-package/ &&
        cp LICENSE target/universal-package/ &&
        cp README.md target/universal-package/ &&
        cp target/Makelangelo-*-with-dependencies.jar target/universal-package/ &&
        cd target/universal-package/ &&
        7z a -tzip Makelangelo.zip . &&
        mv Makelangelo.zip ../.. 

    - name: Prepare target/package for upload
      shell: bash
      run: |
        mkdir -p target/package &&
        cp src/main/package/*.bat target/package/ &&
        cp src/main/package/start* target/package/ &&
        cp src/main/package/thankyou.* target/package/ &&
        cp CONTRIBUTING.md target/package/ &&
        cp LICENSE target/package/ &&
        cp README.md target/package/ 

    - name: Deploy universal release
      if: github.repository == 'MarginallyClever/Makelangelo-software' && github.ref == 'refs/heads/master'
      uses: WebFreak001/deploy-nightly@v3.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ env.UPLOAD_URL }}
        release_id: ${{ env.RELEASE_ID }}
        asset_path: Makelangelo.zip
        asset_name: Makelangelo-nightly-${{ github.run_id }}.zip
        asset_content_type: application/zip
        max_releases: 1

    - name: Upload artifact for package
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jar-${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.time }}
        retention-days: 1
        path: |
          src/main/package/jpackage*
          src/main/package/logo*
          LICENSE
          README
          target/package/*
        if-no-files-found: warn
        compression-level: 6
        overwrite: true

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Generate timestamp
      id: timestamp
      run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: actions/download-artifact@v4.1.7
      with:
        name: jar-${{ github.run_id }}-${{ github.job }}-${{ env.time }}

    - name: Build installation package
      shell: bash
      run: |
        set -x
        set -o pipefail
        APP_VERSION=$(ls -1 target/package/Makelangelo-*-with-dependencies.jar | sed "s/.*Makelangelo-\([^-]*\)-with-dependencies.jar/\1/") &&
        sed -i.bak "s/\(--app-version\).*/\1 $APP_VERSION/" src/main/package/jpackage.cfg &&
        jpackage "@src/main/package/jpackage.cfg" "@src/main/package/jpackage-${{matrix.os}}.cfg" --main-jar "Makelangelo-$APP_VERSION-with-dependencies.jar" &&
        BINARY=$(find . -maxdepth 1 -iname 'makelangelo*' | grep -E '(msi$|dmg$|deb$)' | sed "s,./,," | head -1) &&
        BINARY_NIGHTLY=$(echo $BINARY | sed 's/[Mm]akelangelo\(.*\)\.\(.*\)/\Makelangelo-nightly-$$.\2/') &&
        echo "BINARY=$BINARY" | tee -a $GITHUB_ENV &&
        echo "BINARY_NIGHTLY=$BINARY_NIGHTLY" | tee -a $GITHUB_ENV

    - name: Deploy installation release
      uses: WebFreak001/deploy-nightly@v3.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ env.UPLOAD_URL }}
        release_id: ${{ env.RELEASE_ID }}
        asset_path: ${{ env.BINARY }}
        asset_name: ${{ env.BINARY_NIGHTLY }}
        asset_content_type: application/zip
        max_releases: 1

    - name: Upload artifact for testing purpose
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "${{ env.BINARY }}-${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.time }}"
        retention-days: 2
        path: ${{ env.BINARY }}
    - name: Final Joke
      run: |
            echo "Processus de build terminé ! N'oubliez pas, même le meilleur code a une 'byte' d'humour ! 😄"